module.exports = {
  //Commands 58
  //SAFE Commands 25
  Sa: require('./sa'),
  Pat: require('./pat'),
  Cry: require('./cry'),
  Say: require('./say'),
  Hug: require('./hug'),
  Dab: require('./dab'),
  RPS: require('./rps'),
  Tea: require('./tea'),
  Coin: require('./coin'),
  Slap: require('./slap'),
  Help: require('./help'),
  Ping: require('./ping'),
  Turn: require('./turn'),
  Dice: require('./dice'),
  Date: require('./date'),
  Kick: require('./kick'),
  Kiss: require('./kiss'),
  Loli: require('./loli'),
  Lauh: require('./laugh'),
  Dance: require('./dance'),
  Punch: require('./punch'),
  Urban: require('./urban'),
  Order: require('./order'),
  Spank: require('./spank'),
  Panic: require('./panic'),
  Blush: require('./blush'),
  Github: require('./github'),
  Lolito: require('./lolito'),
  Avatar: require('./avatar'),
  Attach: require('./attach'),
  Cursed: require('./cursed'),
  Handhold: require('./handhold'),
  Noticeme: require('./noticeme'),
  Ignoreme: require('./ignoreme'),
  Translate: require('./translate'),

  //NSFW Commands 8
  Cum: require('./cum'),
  Suck: require('./suck'),
  Nsfw: require('./nsfw'),
  Fuck: require('./fuck'),
  Cunni: require('./cunni'),
  Sauce: require('./sauce'),
  Undress: require('./undress'),
  Urbansfw: require('./urbansfw'),
  Masturbate: require('./masturbate'),

  //Music Commands 4
  Join: require('./join'),
  Stop: require('./stop'),
  Play: require('./play'),
  Queue: require('./queue'),


  //ADMIN NSFW Commands 6
  Scum: require('./scum'),
  Ssuck: require('./ssuck'),
  Sfuck: require('./sfuck'),
  Scunni: require('./scunni'),
  Sundress: require('./sundress'),
  Smasturbate: require('./smasturbate'),

  //ADMIN Commands 12
  Spat: require('./spat'),
  Sdab: require('./sdab'),
  Shug: require('./shug'),
  Scry: require('./scry'),
  Sdab: require('./sdab'),
  Shug: require('./shug'),
  Stea: require('./stea'),
  Sslap: require('./sslap'),
  Purge: require('./purge'),
  Skiss: require('./skiss'),
  Skick: require('./skick'),
  Sblush: require('./sblush'),
  Spanic: require('./spanic'),
  Sspank: require('./sspank'),
  Slaugh: require('./slaugh'),
  Spunch: require('./spunch'),
  Sdance: require('./sdance'),
  Prefix: require('./prefix'),
  Scursed: require('./scursed'),
  Shandhold: require('./shandhold'),
  NewCommand: require('./newcommand'),
};