module.exports = {
  //Commands 58
  //SAFE Commands 25
  Sa: require('./sa'),
  Ban: require('./ban'),
  Check: require('./check'),
  Suggest: require('./suggest'),
  Server: require('./server'),
  User: require('./user'),
  Canvas: require('./canvas'),
  Latest: require('./latest'),
  Color: require('./color'),
  Execution: require('./execution'),
  Say: require('./say'),
  Status: require('./status'),
  Owo: require('./owo'),
  Poll: require('./poll'),
  RPS: require('./rps'),
  Coin: require('./coin'),
  Help: require('./help'),
  Ping: require('./ping'),
  Emotes: require('./emotes'),
  Ship: require('./ship'),
  Pun: require('./pun'),
  Clapify: require('./clapify'),
  Reverse: require('./reverse'),
  Clever: require('./clever'),
  Inspire: require('./inspire'),
  Leet: require('./leet'),
  Fchan: require('./fchan'),
  Turn: require('./turn'),
  Dice: require('./dice'),
  Date: require('./date'),
  Loli: require('./loli'),
  Urban: require('./urban'),
  Count: require('./count'),
  Order: require('./order'),
  Github: require('./github'),
  Reddit: require('./reddit'),
  Lolito: require('./lolito'),
  Avatar: require('./avatar'),
  Random: require('./random'),
  Noticeme: require('./noticeme'),
  Ignoreme: require('./ignoreme'),
  Translate: require('./translate'),

  //NSFW Commands 3
  Nsfw: require('./nsfw'),
  Sauce: require('./sauce'),
  Urbansfw: require('./urbansfw'),

  //Music Commands 4
  Join: require('./join'),
  Stop: require('./stop'),
  Play: require('./play'),
  Queue: require('./queue'),

  //ADMIN Commands 3
  Insert: require('./insert'),
  Prefix: require('./prefix'),
  Purge: require('./purge'),
  Create: require('./create'),
  Delete: require('./delete'),
};